/*

 SRC/DIFFICULTYMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : difficulty.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define difficultyMapWidth 20
#define difficultyMapHeight 18
#define difficultyMapBank 0

extern unsigned char difficultyMap[];

/* End of SRC/DIFFICULTYMAP.H */
