/*

 SRC/DIFFICULTYIMAGES.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 12
   Tile set      : difficulty.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define difficultyImagesWidth 6
#define difficultyImagesHeight 12
#define difficultyImagesBank 0

extern unsigned char difficultyImages[];

/* End of SRC/DIFFICULTYIMAGES.H */
