/*

 SRC/INTROMAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : title.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define introMap1Width 20
#define introMap1Height 18
#define introMap1Bank 0

extern unsigned char introMap1[];

/* End of SRC/INTROMAP1.H */
