/*

 SRC/INTROMAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : title.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define introTiles3Width 20
#define introTiles3Height 18
#define introTiles3Bank 0

extern unsigned char introTiles3[];

/* End of SRC/INTROMAP3.H */
