/*

 LEVEL3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 910 x 18
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level3Width 910
#define level3Height 18
#define level3Bank 0

extern unsigned char level3[];

/* End of LEVEL3.H */
