/*

 LEVEL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 910 x 18
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level2Width 910
#define level2Height 18
#define level2Bank 0

extern unsigned char level2[];

/* End of LEVEL2.H */
