/*

 SRC/MAP_MENU.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : title.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_menuWidth 20
#define map_menuHeight 18
#define map_menuBank 0

extern unsigned char map_menu[];

/* End of SRC/MAP_MENU.H */
