/*

 SRC/MENUMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Dev\git\_Projects\bitbitjam2017\res\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define menuMapWidth 20
#define menuMapHeight 18
#define menuMapBank 0

extern unsigned char menuMap[];

/* End of SRC/MENUMAP.H */
