/*

 SRC/OUTROMAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : outro1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define outroMap1Width 20
#define outroMap1Height 18
#define outroMap1Bank 0

extern unsigned char outroMap1[];

/* End of SRC/OUTROMAP1.H */
