/*

 SRC/OUTROMAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : title.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define outroMap3Width 20
#define outroMap3Height 18
#define outroMap3Bank 0

extern unsigned char outroMap3[];

/* End of SRC/OUTROMAP3.H */
