/*

 SRC/OUTROMAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : outro2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define outroMap2Width 20
#define outroMap2Height 18
#define outroMap2Bank 0

extern unsigned char outroMap2[];

/* End of SRC/OUTROMAP2.H */
