/*

 SRC/TUTORIALMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 24 x 18
   Tile set      : tutorial.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define tutorialMapWidth 24
#define tutorialMapHeight 18
#define tutorialMapBank 0

extern unsigned char tutorialMap[];

/* End of SRC/TUTORIALMAP.H */
